weather_app/__init__.py
from flask import Flask
from os import path

def create_app():
  app = Flask(__name__)
  app.config['SECRET_KEY'] = 'secret_key'

  from .views import views
  app.register_blueprint(views, url_prefix='/')

  return app

weather_app/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from .weather import get_lat_lon, get_current_weather, api_key

views = Blueprint('views', __name__)

class city_name(FlaskForm):
  name = StringField('City Name: ', validators=[DataRequired()])
  country_name = StringField('Country Name: ', validators=[DataRequired()])
  submit = SubmitField('Submit')

@views.route('/')
def home():
  return render_template('index.html')

@views.route('/weather', methods=["POST", "GET"])
def weather():
  name = None
  country_name = None
  form = city_name()

  if request.method == "POST":
    if form.validate_on_submit():
      name = form.name.data
      form.name.data = ''
      country_name = form.country_name.data
      form.country_name.data = ''
      
      lat, lon = get_lat_lon(name, 'ON', country_name, api_key)
      data = get_current_weather(lat, lon, api_key)
      
      return render_template("weather.html", name=name, form=form, data=data)

  return render_template("weather.html", form=form)

weather_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block content %}{% endblock %}
</body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

weather_app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Weather App</h1> 

      
      <div id="map" style="height: 400px;"></div>
      <script>
        // Initialize and add the map
        function initMap()
        {
          const map = new google.maps.Map(document.getElementById('map'),
          {
            center: { lat: -34.397, lng: 150.644 },
            zoom: 3
          });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_GOOGLE_MAPS_API_KEY&callback=initMap" async defer></script>

      <br><br><br><br>
      <a class="btn btn-secondary" href="{{ url_for('views.weather') }}" role="button">Check Weather</a>

    </div>
  </div>
</div>

{% endblock %}

weather_app/templates/weather.html
{% extends "base.html" %}

{% block title %}Your Weather{% endblock %}

{% block content %}
    {% if name %}
        <h1>Weather of {{ name }}</h1>

        <p>Sky: {{ data.main }}</p> <br>
        <p>Min Temperature: {{ data.temp_min }}</p> <br>
        <p>Max Temperature: {{ data.temp_max }}</p> <br>

        <br><br>
        <a class="btn btn-secondary" href="{{ url_for('views.weather') }}" role="button">Check Weather Again</a>

    {% else %}
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label(class="form.label") }}
            {{ form.name(size=20, class="form-control") }}
            <br><br>
            {{ form.country_name.label(class="form.label") }}
            {{ form.country_name(size=20, class="form-control") }}
            <br><br>
            {{ form.submit(class="btn btn-dark") }}
        </form>
    {% endif %}
{% endblock %}